[package]
name = "fuseki"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.73.0"

[dependencies]
libremarkable = {git="https://github.com/canselcik/libremarkable"}
env_logger = "0.11"
log = "0.4"
gtp = "0.1.2"
lazy_static = "1"