name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/toltec-dev/rust:v3.1
      options: --user root
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4        
      - name: Build
        run: cargo build --release